# Original workflow created by SpanishPear:
# https://github.com/SpanishPear/yew_worker_stylist_actions_pages_template/blob/main/.github/workflows/deploy.yml

name: Publish on GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Tailwind
      run: npm i -g tailwindcss
    
    - name: Build CSS
      run: tailwind -i styles.css -o tailwind.css

    - name: Install Trunk
      uses: jetli/trunk-action@v0.4.0

    - name: Run Trunk
      run: trunk build --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GHPAGES_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs # Source
        force_orphan: true
        cname: calculator.eamonburns.com
